import type { Octokit } from "@octokit/rest";
import type { IssueRef } from "../adapters/github.js";
import { ensureLabels, labelsFor } from "../adapters/labels.js";
import { upsertPullRequest } from "../adapters/pulls.js";
import type { DeliverResult, GateResult } from "../pipeline/artifacts.js";
import type { RunContext } from "../pipeline/run.js";
import { branchName, commitFixBranch } from "./branch.js";
import { githubLoginLookup, type LoginLookup, reviewerFor } from "./owners.js";
import { renderPrBody } from "./prBody.js";

export interface DeliverOptions {
	/** Checkout of the repo being fixed. */
	root: string;
	headSha: string;
	ctx: RunContext;
	gate: GateResult;
	/** Without a client, or with `dryRun`, nothing is written to GitHub. A client still serves reads. */
	octokit: Octokit | undefined;
	dryRun: boolean;
	/** The repo and issue. Needed whenever there is an octokit. */
	ref?: IssueRef;
	/** GitHub login of the reporter, who is never the reviewer. Read from the issue when omitted. */
	issueAuthor?: string;
	/** Email to login, for the git-blame reviewer fallback. Defaults to GitHub user search. */
	lookupLogin?: LoginLookup;
	/** Branch the PR targets. Defaults to the repo's default branch. */
	base?: string;
}

/** One line of text with no markup that could change the title. */
const oneLine = (text: string) => text.replace(/\s+/g, " ").trim();

/**
 * Stage 7: turns a fix the gate approved into a branch and a pull request. A `ready_pr` or
 * `draft_pr` opens a PR, or updates the open one for the branch. `diagnosis_only` opens nothing,
 * because another module posts the diagnosis. A dry run applies the fix locally and reports what
 * it would have written.
 */
export async function deliverFix(opts: DeliverOptions): Promise<DeliverResult> {
	const { ctx, gate, octokit, ref } = opts;

	if (gate.delivery === "diagnosis_only") {
		return {
			status: "skipped",
			detail: "no PR: the diagnosis is posted instead",
		};
	}

	const fix = ctx.artifacts.fix;

	// The gate does not stop a draft for a run that fixed nothing, so Deliver does.
	if (fix?.status !== "fixed" || fix.diff.trim() === "") {
		return {
			status: "skipped",
			detail: "no PR: there is no passing fix to deliver",
		};
	}

	if (octokit && !ref) {
		throw new Error(
			"deliverFix needs the repo and issue (ref) to use GitHub",
		);
	}

	const n = ctx.issue.number;

	const branch = branchName(n);

	const draft = gate.delivery === "draft_pr";

	const title = `Fix #${n}: ${oneLine(ctx.issue.title)}`.slice(0, 120);

	const body = renderPrBody({ ctx, gate });

	const labels = labelsFor(
		gate.delivery,
		ctx.artifacts.intake,
		ctx.artifacts.reproduction?.area,
	);

	const issueAuthor =
		opts.issueAuthor ??
		(octokit && ref
			? (
					await octokit.issues.get({
						owner: ref.owner,
						repo: ref.repo,
						issue_number: ref.issue,
					})
				).data.user?.login
			: undefined);

	const reviewer = await reviewerFor({
		root: opts.root,
		changedFiles: fix.filesChanged,
		issueAuthor,
		lookupLogin:
			opts.lookupLogin ??
			(octokit ? githubLoginLookup(octokit) : undefined),
	});

	// The only client that may write. A dry run leaves it out, so it cannot reach a write call.
	const write =
		octokit && ref && !opts.dryRun
			? { octokit, repo: { owner: ref.owner, repo: ref.repo } }
			: undefined;

	if (write) await ensureLabels(write.octokit, write.repo, labels);

	const built = await commitFixBranch({
		root: opts.root,
		headSha: opts.headSha,
		diff: fix.diff,
		branch,
		message: `${title}\n\nGenerated by FixLoop for #${n}.`,
		write,
	});

	const who = reviewer.reviewer
		? `@${reviewer.reviewer} (${reviewer.reason})`
		: `none (${reviewer.reason})`;

	if (!write) {
		return {
			status: "dry_run",
			branch,
			detail: [
				`Would open a ${draft ? "draft" : "ready"} PR from ${branch}.`,
				`title: ${title}`,
				`labels: ${labels.join(", ")}`,
				`reviewer: ${who}`,
				`files: ${built.files.map((f) => `${f.path} (${f.status})`).join(", ")}`,
				"body:",
				body,
			].join("\n"),
		};
	}

	const base =
		opts.base ??
		(await write.octokit.repos.get(write.repo)).data.default_branch;

	const pr = await upsertPullRequest(write.octokit, write.repo, {
		branch,
		base,
		title,
		body,
		draft,
		labels,
		reviewer: reviewer.reviewer,
	});

	return {
		status: pr.status,
		url: pr.url,
		branch,
		detail: [
			`PR #${pr.number} ${pr.status === "pr_opened" ? "opened" : "updated"} as ${draft ? "a draft" : "ready for review"}.`,
			`Reviewer: ${who}.`,
			...pr.notes,
		].join(" "),
	};
}
